name: Go

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v cmd/generate/main.go

    - name: Test
      run: go test -v cmd/generate/main.go
      
    - name: Generate README.md
      run: FIRESTORE_KEY=${{ secrets.FIRESTORE_KEY }} TELEGRAM_BOT_CHAT_ID=${{ secrets.TELEGRAM_BOT_CHAT_ID }} TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} ./main
    - name: Update README.md
      run: |
        git config --global user.email "nguyenduyquang06@gmail.com"
        git config --global user.name "Github Action bot"
        git add README.md
        git commit -m "Update README.md"
